// Wallet Actions
export const FETCH_RESELLER_WALLETS_REQUEST = 'FETCH_RESELLER_WALLETS_REQUEST';
export const FETCH_RESELLER_WALLETS_SUCCESS = 'FETCH_RESELLER_WALLETS_SUCCESS';
export const FETCH_RESELLER_WALLETS_FAIL = 'FETCH_RESELLER_WALLETS_FAIL';

export const FETCH_ALL_WALLETS_REQUEST = 'FETCH_ALL_WALLETS_REQUEST';
export const FETCH_ALL_WALLETS_SUCCESS = 'FETCH_ALL_WALLETS_SUCCESS';
export const FETCH_ALL_WALLETS_FAIL = 'FETCH_ALL_WALLETS_FAIL';

export const FETCH_WALLET_DETAILS_REQUEST = 'FETCH_WALLET_DETAILS_REQUEST';
export const FETCH_WALLET_DETAILS_SUCCESS = 'FETCH_WALLET_DETAILS_SUCCESS';
export const FETCH_WALLET_DETAILS_FAIL = 'FETCH_WALLET_DETAILS_FAIL';

export const FETCH_WALLET_STATISTICS_REQUEST = 'FETCH_WALLET_STATISTICS_REQUEST';
export const FETCH_WALLET_STATISTICS_SUCCESS = 'FETCH_WALLET_STATISTICS_SUCCESS';
export const FETCH_WALLET_STATISTICS_FAIL = 'FETCH_WALLET_STATISTICS_FAIL';

export const CREATE_WALLET_REQUEST = 'CREATE_WALLET_REQUEST';
export const CREATE_WALLET_SUCCESS = 'CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAIL = 'CREATE_WALLET_FAIL';

export const ADD_BALANCE_REQUEST = 'ADD_BALANCE_REQUEST';
export const ADD_BALANCE_SUCCESS = 'ADD_BALANCE_SUCCESS';
export const ADD_BALANCE_FAIL = 'ADD_BALANCE_FAIL';

export const ADD_PAYMENT_REQUEST = 'ADD_PAYMENT_REQUEST';
export const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS';
export const ADD_PAYMENT_FAIL = 'ADD_PAYMENT_FAIL';

export const DEDUCT_BALANCE_REQUEST = 'DEDUCT_BALANCE_REQUEST';
export const DEDUCT_BALANCE_SUCCESS = 'DEDUCT_BALANCE_SUCCESS';
export const DEDUCT_BALANCE_FAIL = 'DEDUCT_BALANCE_FAIL';

export const DEDUCT_PAYMENT_REQUEST = 'DEDUCT_PAYMENT_REQUEST';
export const DEDUCT_PAYMENT_SUCCESS = 'DEDUCT_PAYMENT_SUCCESS';
export const DEDUCT_PAYMENT_FAIL = 'DEDUCT_PAYMENT_FAIL';

export const SET_DEFAULT_WALLET_REQUEST = 'SET_DEFAULT_WALLET_REQUEST';
export const SET_DEFAULT_WALLET_SUCCESS = 'SET_DEFAULT_WALLET_SUCCESS';
export const SET_DEFAULT_WALLET_FAIL = 'SET_DEFAULT_WALLET_FAIL';

export const ACTIVATE_WALLET_REQUEST = 'ACTIVATE_WALLET_REQUEST';
export const ACTIVATE_WALLET_SUCCESS = 'ACTIVATE_WALLET_SUCCESS';
export const ACTIVATE_WALLET_FAIL = 'ACTIVATE_WALLET_FAIL';

export const DEACTIVATE_WALLET_REQUEST = 'DEACTIVATE_WALLET_REQUEST';
export const DEACTIVATE_WALLET_SUCCESS = 'DEACTIVATE_WALLET_SUCCESS';
export const DEACTIVATE_WALLET_FAIL = 'DEACTIVATE_WALLET_FAIL';

export const TRANSFER_BETWEEN_WALLETS_REQUEST = 'TRANSFER_BETWEEN_WALLETS_REQUEST';
export const TRANSFER_BETWEEN_WALLETS_SUCCESS = 'TRANSFER_BETWEEN_WALLETS_SUCCESS';
export const TRANSFER_BETWEEN_WALLETS_FAIL = 'TRANSFER_BETWEEN_WALLETS_FAIL';
